### ISSUE TITLE
Publish to `npm` through GitHub Packages

### ISSUE THREAD

**Issue by tsalo** [ME-ICA/rica#28]
### Summary
This is just a thought, and I don't even know what it would entail, but it would be cool to publish `rica` to `npm` using GitHub Packages.

**Comment by eurunuela** [comment]
Why would we want to do that? I don't see Rica as a package you can import to another JS package.

I may be missing your point.

**Comment by eurunuela** [comment]
Yes, that sounds right. I'll have to do some research to learn how.

**Comment by eurunuela** [comment]
Yes. I agree. It probably is as easy as deploying to Netlify so I'll probably do it to kill some time while I wait for some analysis to finish.
