### ISSUE TITLE
Component spatial and temporal maps absent from RICA webapp

### ISSUE THREAD

**Issue by DaveOC90** [ME-ICA/rica#71]
### Summary

When I load a tedana output (v 24.0.1) into RICA (v1.1.1) via the web app, and click on a section of the pie chart, or on a dot in the Rho/Kappa plot, the component's spatial and temporal maps do not appear on the right. See screenshot:

![Screenshot 2024-05-22 at 1 51 26 PM](https://github.com/ME-ICA/rica/assets/6143678/b04d22d9-61ab-419e-970b-65f786aa0212)

I have tried locally on my Mac with Chrome and Firefox and on a server running Ubuntu with Firefox. Can you offer any advice on how to resolve it?

Thanks,

Dave

**Comment by eurunuela** [comment]
Hi Dave, thank you for reaching out!

Just to make sure, did the folder you provided contain the images?

Could you share your tedana output folder with me so I can try to replicate your issue on my end?

Thanks!

Eneko

**Comment by DaveOC90** [comment]
Hi Eneko,

Thanks for your quick response! The folder does contain the images, and the html report accurately renders the component images. See here for a zip file of the tedana output (minus the niftis to keep it smaller): https://drive.google.com/file/d/10ZBPze0I9xKVyFN1txcqjdhOjXy058bY/view?usp=drive_link 

Let me know if I can provide any other info/data.

Dave

**Comment by eurunuela** [comment]
Hey Dave,

I have fixed the issue.

Could you please test with a different dataset using the following link?

https://deploy-preview-72--rica-fmri.netlify.app/

As soon as you give me a thumbs up I will make the changes public to everyone.

Thank you!

Eneko

**Comment by DaveOC90** [comment]
Hi Eneko,

That fix worked for me, thank you! Thanks for developing the tool as well, I think it will speed up manual reclassification quite a bit.

Dave

**Comment by eurunuela** [comment]
In that case, I will cut a new release.

Glad you're finding Rica useful. I built it because I found the process of manually selecting with tedana's reports really annoying.
